name: Test Suite

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: "actions/checkout@v4"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
          cache: pip

      - name: Ensure latest pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install hatch
          hatch env create

      - name: Code health checks
        run: |
          hatch run lint
          hatch run typing

      - name: Test and coverage checks
        run: |
          hatch run cov

      - name: Refresh coveralls
        if: github.event_name == 'push'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls
